# Generated by Django 2.0.4 on 2018-07-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='conteudo',
            field=models.TextField(blank=True, default='', help_text='...', null=True, verbose_name='Conteúdo do arquivo'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='relatorio',
            field=models.TextField(blank=True, default='', help_text='...', null=True, verbose_name='Relatório:'),
        ),
        migrations.AlterField(
            model_name='solucao',
            name='solucao',
            field=models.CharField(blank=True, default='', help_text='...', max_length=255, null=True, verbose_name='Valor'),
        ),
    ]
