# Generated by Django 2.0.4 on 2018-11-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0002_auto_20180728_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicada',
            options={'ordering': ['questao__numero'], 'verbose_name': 'Questao Aplicada', 'verbose_name_plural': 'Questões Aplicadas'},
        ),
        migrations.AlterModelOptions(
            name='aplicado',
            options={'ordering': ['algoritmo__numero'], 'verbose_name': 'Algoritmo Aplicado', 'verbose_name_plural': 'Algoritmos Aplicados'},
        ),
    ]
