# Generated by Django 2.0.4 on 2018-07-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cargo',
            field=models.CharField(choices=[('professor', 'Professor(a)'), ('aluno', 'Aluno(a)'), ('admin', 'Administrador(a)')], max_length=25, verbose_name='Cargo'),
        ),
    ]
