# Generated by Django 2.1.3 on 2019-04-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_auto_20180731_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ativo',
            field=models.BooleanField(default=True, help_text='...'),
        ),
        migrations.AddField(
            model_name='variavel',
            name='ativo',
            field=models.BooleanField(default=True, help_text='...'),
        ),
    ]
