# Generated by Django 2.1.3 on 2019-04-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0003_auto_20190412_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='variavel',
            name='ativo',
        ),
    ]
