# Generated by Django 2.0.4 on 2018-07-26 21:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conhecimento',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='...', max_length=255, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, help_text='...')),
                ('descricao', models.TextField(blank=True, default=None, help_text='...', null=True, verbose_name='Descrição')),
                ('inicio', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='...', null=True, verbose_name='Data de Início')),
                ('fim', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='...', null=True, verbose_name='Data de Fim')),
            ],
            options={
                'verbose_name': 'Conhecimento',
                'verbose_name_plural': 'Conhecimentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, default=None, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, help_text='...', verbose_name='Ativo')),
                ('descricao', models.TextField(blank=True, default=None, null=True, verbose_name='Descrição')),
                ('inicio', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='...', null=True, verbose_name='Data de Início')),
                ('fim', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='...', null=True, verbose_name='Data de Fim')),
                ('questao', models.IntegerField(default=0, editable=False)),
                ('alunos', models.ManyToManyField(blank=True, help_text='...', limit_choices_to={'cargo': 'aluno'}, related_name='na_turma', to=settings.AUTH_USER_MODEL)),
                ('conhecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='instituicao.Conhecimento')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='conhecimento',
            name='instituicao',
            field=models.ForeignKey(help_text='...', on_delete=django.db.models.deletion.CASCADE, related_name='conhecimentos', to='instituicao.Instituicao'),
        ),
        migrations.AddField(
            model_name='conhecimento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='conhecimento',
            unique_together={('instituicao', 'nome')},
        ),
    ]
