# Generated by Django 2.0.4 on 2018-07-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problema',
            name='proposta',
            field=models.TextField(blank=True, default=None, help_text='A proposta pode ser em texto, markdown ou latex.', null=True, verbose_name='Proposta'),
        ),
        migrations.AddField(
            model_name='problema',
            name='solucao',
            field=models.TextField(blank=True, default=None, help_text='...', null=True, verbose_name='Solução'),
        ),
        migrations.AlterField(
            model_name='problema',
            name='observacao',
            field=models.TextField(blank=True, default=None, help_text='...', null=True, verbose_name='Observação'),
        ),
    ]
