# Generated by Django 2.0.4 on 2018-08-17 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('situacao', '0002_auto_20180731_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='referencia',
            field=models.CharField(help_text='...', max_length=255, verbose_name='Referência'),
        ),
        migrations.AlterUniqueTogether(
            name='problema',
            unique_together={('usuario', 'referencia')},
        ),
    ]
