# Generated by Django 2.0.4 on 2018-11-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacao', '0003_auto_20180817_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indice',
            options={'ordering': ['ordem', 'superior__nome', 'nome'], 'verbose_name': 'Indice', 'verbose_name_plural': 'Indices'},
        ),
        migrations.AddField(
            model_name='indice',
            name='ordem',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
