# Generated by Django 2.0.4 on 2018-11-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacao', '0004_auto_20181112_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='problema',
            name='uso',
            field=models.PositiveSmallIntegerField(blank=True, help_text='...', null=True, verbose_name='Uso'),
        ),
    ]
