# Generated by Django 2.0.4 on 2018-11-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacao', '0005_problema_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='problema',
            name='usos',
            field=models.CharField(blank=True, help_text='...', max_length=2550, null=True, verbose_name='Usos'),
        ),
    ]
