# Generated by Django 2.0.4 on 2018-11-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacao', '0006_problema_usos'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='uso',
            field=models.PositiveSmallIntegerField(blank=True, help_text='...', null=True, verbose_name='Uso'),
        ),
        migrations.AddField(
            model_name='programa',
            name='usos',
            field=models.CharField(blank=True, help_text='...', max_length=2550, null=True, verbose_name='Usos'),
        ),
    ]
