# Generated by Django 2.1.3 on 2018-12-13 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('situacao', '0007_auto_20181114_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indice',
            name='superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subindices', to='situacao.Indice'),
        ),
    ]
