# Generated by Django 2.1.3 on 2019-04-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('situacao', '0009_auto_20190412_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='indice',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='simulacao',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='texto',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='valoraleatorio',
            name='ativo',
        ),
    ]
