# Generated by Django 2.0.4 on 2018-07-26 21:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituicao', '0001_initial'),
        ('tarefa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgoritmoStatus',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iniciou', models.DateTimeField(blank=True, default=None, help_text='...', null=True, verbose_name='DataHora Início')),
                ('tempo', models.TimeField(blank=True, default=None, help_text='...', null=True, verbose_name='Tempo')),
                ('ativo', models.BooleanField(default=True, help_text='...', verbose_name='Ativa')),
                ('aplicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_aplicado', to='tarefa.Aplicado')),
            ],
            options={
                'verbose_name': 'Status do Algoritmo',
                'verbose_name_plural': 'Status do Algoritmo',
                'ordering': ['aplicado__usuario__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Ementa',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField(blank=True, default=None, help_text='...', null=True, verbose_name='Texto')),
                ('conhecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ementas', to='instituicao.Conhecimento')),
            ],
            options={
                'verbose_name': 'Ementa',
                'verbose_name_plural': 'Ementas',
            },
        ),
        migrations.CreateModel(
            name='QuestaoStatus',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iniciou', models.DateTimeField(blank=True, default=None, help_text='...', null=True, verbose_name='DataHora Início')),
                ('tempo', models.TimeField(blank=True, default=None, help_text='...', null=True, verbose_name='Tempo')),
                ('tentativa', models.PositiveSmallIntegerField(blank=True, default=0, help_text='...', null=True, verbose_name='Tentativa')),
                ('ativo', models.BooleanField(default=True, help_text='...', verbose_name='Ativa')),
                ('aplicada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='tarefa.Aplicada')),
            ],
            options={
                'verbose_name': 'Status da Questão',
                'verbose_name_plural': 'Status da Questões',
                'ordering': ['aplicada__usuario__last_name'],
            },
        ),
    ]
