# Generated by Django 2.1.3 on 2019-04-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_ementa_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ementa',
            name='ativo',
        ),
    ]
